name: tunuk-data-producer
title: Tunuk DataProducer
version: '0.2.4'
summary: IoT data producer for public transportation units monitoring
description: |
  Tunuk DataProducer is a software application to extract, filter, process
  and send data to a message receiver. Tunuk leads an adaptative model
  where different controllers can be selected to extract data from CANBus
  sensors, APC devices, GPS and more, depending on your gateway capabilities.

base: core18
grade: stable
confinement: strict
apps:
  tunuk-data-producer:
    command:
      java -jar $SNAP/jar/tunuk-data-producer-1.0-SNAPSHOT.jar
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
      - cups-control

parts:
  tunuk-data-producer:
    plugin: maven
    source: .
    source-tag: release-$SNAPCRAFT_PROJECT_VERSION


